In [9]:
import pandas as pd

In [10]:
data = pd.read_csv('data/covtype.data', header=None)
data.shape

(581012, 55)

In [11]:
columns = ['elevation', 'aspect', 'slope', 'hor_dist_to_hydro', 'vert_dist_to_hydro', 'hor_dist_to_roadways', 'hillshade_9am', 'hillshade_noon', 'hillshade_3pm', 'hor_dist_to_fire_points', 'wilderness_area_1', 'wilderness_area_2', 'wilderness_area_3', 'wilderness_area_4']

soil_columns = ['soil_type_' + str(i) for i in range(1, 41)]

columns = columns + soil_columns + ['cover_type']

In [12]:
data.columns = columns
data.head()

,elevation,aspect,slope,hor_dist_to_hydro,vert_dist_to_hydro,hor_dist_to_roadways,hillshade_9am,hillshade_noon,hillshade_3pm,hor_dist_to_fire_points,...,soil_type_32,soil_type_33,soil_type_34,soil_type_35,soil_type_36,soil_type_37,soil_type_38,soil_type_39,soil_type_40,cover_type
0,2596,51,3,258,0,510,221,232,148,6279,...,0,0,0,0,0,0,0,0,0,5
1,2590,56,2,212,-6,390,220,235,151,6225,...,0,0,0,0,0,0,0,0,0,5
2,2804,139,9,268,65,3180,234,238,135,6121,...,0,0,0,0,0,0,0,0,0,2
3,2785,155,18,242,118,3090,238,238,122,6211,...,0,0,0,0,0,0,0,0,0,2
4,2595,45,2,153,-1,391,220,234,150,6172,...,0,0,0,0,0,0,0,0,0,5

In [13]:
train_set = data.iloc[:11340,:]
valid_set = data.iloc[11340:(11340+3780),:]
test_set = data.iloc[-565892:,:]

In [14]:
X_train = train_set.iloc[:,:-1]
y_train = train_set.iloc[:,-1]

X_valid = valid_set.iloc[:,:-1]
y_valid = valid_set.iloc[:,-1]

X_test = test_set.iloc[:,:-1]
y_test = test_set.iloc[:,-1]

%store X_train
%store y_train
%store X_valid
%store y_valid
%store X_test
%store y_test

Stored 'X_train' (DataFrame)
Stored 'y_train' (Series)
Stored 'X_valid' (DataFrame)
Stored 'y_valid' (Series)
Stored 'X_test' (DataFrame)
Stored 'y_test' (Series)